modLoader = "javafml" #mandatory
loaderVersion = "[45,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
[[mods]] #mandatory
modId = "lostfeatures" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Lost Features" #mandatory
logoFile = "icon.png" #optional
credits = "Big thanks to sheslong for most textures!"
authors = "KaboomRoads" #optional
description = '''
This mod adds features that never made it into the game!
'''
[[dependencies.lostfeatures]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[45,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.lostfeatures]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.4,1.20)"
ordering = "NONE"
side = "BOTH"
